services:
#    petkopara_crud.example:
#        class: Petkopara\Bundle\CrudBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    petkopara_crud.twig_extension:
        class: Petkopara\CrudGeneratorBundle\Twig\CrudTemplateExtension
        tags:
            - { name: twig.extension }